import React, { useEffect, useState } from 'react'
import { CarFront, ClipboardList, Eye, Pencil, Plus, Search, Trash2 } from 'lucide-react'
import type { Invoice, Item } from '../../services/apiServices'
import { api } from '../../services/apiServices'
import { money, shortDate } from '../../lib/utils'
import { Badge, Button, Card, Dialog, EmptyState, Input } from '../../components/ui'
import { type Language, type Toast, t } from '../../lib/app-shared'



export function ItemDetailPage({ language, item, invoices, onBack, onViewInvoice }: { language: Language; item: Item; invoices: Invoice[]; onBack: () => void; onViewInvoice: (invoice: Invoice) => void }) {
  const invoiceRows = invoices.flatMap((invoice) => invoice.details?.filter((detail) => detail.item_id === item.id || detail.item?.id === item.id || detail.item?.name === item.name || detail.name === item.name).map((detail) => ({ invoice, detail })) || [])
  return <><div className="page-heading"><div><button className="back-link" onClick={onBack}>← {t(language, 'services')}</button><div className="eyebrow">Service item profile</div><h1>{item.name}</h1><p>Invoice usage history with date, quantity, and price details.</p></div></div><div className="detail-grid"><Card><div className="detail-label">Service item</div><div className="detail-person"><div className="vehicle-icon" style={{ background: '#fff6dc', color: '#d39d1f' }}><ClipboardList size={19} /></div><div><h2>{item.name}</h2><p>Current listed price: {money(item.price)}</p></div></div></Card><Card><div className="detail-label">Invoices</div><div className="detail-payment"><strong>{invoiceRows.length}</strong><span>invoice line items using this service</span></div></Card><Card><div className="detail-label">Quantity</div><div className="detail-payment"><strong>{invoiceRows.reduce((sum, row) => sum + Number(row.detail.quantity || 0), 0)}</strong><span>total units recorded</span></div></Card></div><Card className="table-card"><div className="card-title detail-section-heading"><div><h2>Invoice summary</h2><p>Date, quantity, and price for every invoice using this item.</p></div><Badge tone="info">{invoiceRows.length} records</Badge></div>{invoiceRows.length ? <div className="table-wrap"><table className="data-table"><thead><tr><th>Invoice</th><th>Date</th><th>Customer</th><th>Vehicle</th><th>Quantity</th><th>Price</th><th>Total</th><th></th></tr></thead><tbody>{invoiceRows.map(({ invoice, detail }, index) => <tr key={`${invoice.id}-${detail.id || index}`}><td><button className="table-link" onClick={() => onViewInvoice(invoice)}>#{invoice.invoice_number}</button></td><td>{shortDate(invoice.date)}</td><td>{invoice.customer?.name || '—'}</td><td>{invoice.car?.number || '—'}</td><td>{detail.quantity}</td><td>{money(detail.price)}</td><td><strong>{money(Number(detail.price) * Number(detail.quantity))}</strong></td><td><Button variant="ghost" size="icon" title="View invoice" onClick={() => onViewInvoice(invoice)}><Eye size={14} /></Button></td></tr>)}</tbody></table></div> : <EmptyState title="No invoice usage found" description="This item has not been used on an invoice yet." />}</Card></>
}