import React, { useEffect, useState } from 'react'
import { CarFront, ClipboardList, Eye, Pencil, Plus, Search, Trash2 } from 'lucide-react'
import type { Car, Customer, Invoice, Item } from '../lib/api'
import { api } from '../lib/api'
import { initials, money, shortDate } from '../lib/utils'
import { Badge, Button, Card, Dialog, EmptyState, Input, Select } from '../components/ui'
import { type Language, type Toast, type CarForm, t } from '../lib/app-shared'
import { InvoiceTable, RelatedInvoices } from './InvoicePages'
import { Pagination } from '../components/Pagination'

export function CustomerDetailPage({ language, customer, cars, invoices, onBack, onViewInvoice, onEditInvoice, onDeleteInvoice, onPrintInvoice }: { language: Language; customer: Customer; cars: Car[]; invoices: Invoice[]; onBack: () => void; onViewInvoice: (invoice: Invoice) => void; onEditInvoice: (invoice: Invoice) => void; onDeleteInvoice: (invoice: Invoice) => Promise<void>; onPrintInvoice: (invoice: Invoice) => void }) {
  const customerCars = cars.filter((car) => car.customer_id === customer.id)
  const customerInvoices = invoices.filter((invoice) => invoice.customer_id === customer.id || invoice.customer?.id === customer.id)
  return <><div className="page-heading"><div><button className="back-link" onClick={onBack}>← {t(language, 'customers')}</button><div className="eyebrow">Customer profile</div><h1>{customer.name}</h1><p>{customer.phone || 'No phone recorded'} · Customer history and related records</p></div></div><div className="detail-grid"><Card><div className="detail-label">{t(language, 'customer')}</div><div className="detail-person"><div className="avatar">{initials(customer.name)}</div><div><h2>{customer.name}</h2><p>{customer.phone || 'No phone recorded'}</p></div></div></Card><Card><div className="detail-label">Vehicles</div><div className="detail-payment"><strong>{customerCars.length}</strong><span>vehicles registered to this customer</span></div></Card><Card><div className="detail-label">Invoices</div><div className="detail-payment"><strong>{customerInvoices.length}</strong><span>invoices in the live records</span></div></Card></div><Card className="table-card"><div className="card-title detail-section-heading"><div><h2>Car summary</h2><p>Vehicles registered under this customer.</p></div><Badge tone="success">{customerCars.length} vehicles</Badge></div>{customerCars.length ? <div className="table-wrap"><table className="data-table"><thead><tr><th>Vehicle</th><th>Make & model</th><th>Service history</th></tr></thead><tbody>{customerCars.map((car) => <tr key={car.id}><td><div className="td-main"><span className="tiny-avatar" style={{ background: '#e8faf4', color: '#1aaf7b' }}><CarFront size={13} /></span><strong>{car.number}</strong></div></td><td>{[car.brand, car.model].filter(Boolean).join(' ') || '—'}</td><td>{customerInvoices.filter((invoice) => invoice.car_id === car.id || invoice.car?.id === car.id).length} invoices</td></tr>)}</tbody></table></div> : <EmptyState title="No vehicles linked" description="Vehicles assigned to this customer will appear here." />}</Card><RelatedInvoices title="Invoice summary" invoices={customerInvoices} onView={onViewInvoice} onEdit={onEditInvoice} onDelete={onDeleteInvoice} onPrint={onPrintInvoice} /></>
}

export function CarDetailPage({ language, car, invoices, onBack, onViewInvoice, onEditInvoice, onDeleteInvoice, onPrintInvoice }: { language: Language; car: Car; invoices: Invoice[]; onBack: () => void; onViewInvoice: (invoice: Invoice) => void; onEditInvoice: (invoice: Invoice) => void; onDeleteInvoice: (invoice: Invoice) => Promise<void>; onPrintInvoice: (invoice: Invoice) => void }) {
  const carInvoices = invoices.filter((invoice) => invoice.car_id === car.id || invoice.car?.id === car.id || invoice.car?.number === car.number)
  return <><div className="page-heading"><div><button className="back-link" onClick={onBack}>← {t(language, 'vehicles')}</button><div className="eyebrow">Vehicle profile</div><h1>{car.number}</h1><p>{[car.brand, car.model].filter(Boolean).join(' ') || 'Vehicle history'} · Related service records</p></div></div><div className="detail-grid"><Card><div className="detail-label">{t(language, 'vehicle')}</div><div className="detail-person"><div className="vehicle-icon"><CarFront size={19} /></div><div><h2>{car.number}</h2><p>{[car.brand, car.model].filter(Boolean).join(' ') || 'No model recorded'}</p></div></div></Card><Card><div className="detail-label">Owner</div><div className="detail-person"><div className="avatar">{initials(car.customer?.name || 'NA')}</div><div><h2>{car.customer?.name || '—'}</h2><p>Registered customer</p></div></div></Card><Card><div className="detail-label">Invoices</div><div className="detail-payment"><strong>{carInvoices.length}</strong><span>service invoices for this vehicle</span></div></Card></div><RelatedInvoices title="Invoice summary" invoices={carInvoices} onView={onViewInvoice} onEdit={onEditInvoice} onDelete={onDeleteInvoice} onPrint={onPrintInvoice} /></>
}

export function CustomersPage({ language, isAdmin, customers, onView, onChange, notify }: { language: Language; isAdmin: boolean; customers: Customer[]; onView: (customer: Customer) => void; onChange: (value: Customer[]) => void; notify: (message: string, kind?: Toast['kind']) => void }) {
  const [query, setQuery] = useState(''); const [page, setPage] = useState(1); const [dialog, setDialog] = useState<'new' | Customer | null>(null); const [deleteId, setDeleteId] = useState<number | null>(null); const pageSize = 6; const filtered = customers.filter((customer) => `${customer.name} ${customer.phone || ''}`.toLowerCase().includes(query.toLowerCase())); const pages = Math.max(1, Math.ceil(filtered.length / pageSize)); const rows = filtered.slice((page - 1) * pageSize, page * pageSize); useEffect(() => setPage(1), [query])
  const save = async (name: string) => { try { const result = typeof dialog === 'object' && dialog ? await api.updateCustomer(dialog.id, { name }) : await api.createCustomer({ name }); onChange(typeof dialog === 'object' && dialog ? customers.map((customer) => customer.id === dialog.id ? { ...customer, ...result.data } : customer) : [{ ...result.data, _count: { invoices: 0, cars: 0 } }, ...customers]); setDialog(null); notify(typeof dialog === 'object' ? 'Customer updated' : 'Customer added') } catch (requestError) { notify(requestError instanceof Error ? requestError.message : 'Could not save customer to the live API.', 'error') } }
  const remove = async () => { if (!deleteId) return; try { await api.deleteCustomer(deleteId); onChange(customers.filter((customer) => customer.id !== deleteId)); setDeleteId(null); notify(t(language, 'customerDeleted')) } catch { notify(t(language, 'customerDeleteError'), 'error') } }
  return <><ListHeading eyebrow={t(language, 'customerDirectory')} title={t(language, 'customers')} description={t(language, 'customerDescription')} actionLabel={t(language, 'addCustomer')} onAction={() => setDialog('new')} /><div className="toolbar"><div className="toolbar-left"><div className="search-box"><Search size={15} /><Input placeholder={t(language, 'searchCustomers')} value={query} onChange={(e) => setQuery(e.target.value)} /></div></div><span style={{ fontSize: 11, color: '#8892a4' }}>{filtered.length} {t(language, 'customers')}</span></div><Card className="table-card"><div className="table-wrap"><table className="data-table"><thead><tr><th>{t(language, 'customer')}</th><th>{t(language, 'phone')}</th><th>{t(language, 'vehicles')}</th><th>{t(language, 'invoices')}</th><th></th></tr></thead><tbody>{rows.map((customer) => <tr key={customer.id}><td><div className="td-main"><span className="tiny-avatar">{initials(customer.name)}</span><strong>{customer.name}</strong></div></td><td>{customer.phone || '—'}</td><td>{customer._count?.cars || 0}</td><td>{customer._count?.invoices || 0}</td><td><div className="table-actions"><Button variant="ghost" size="icon" title="View" onClick={() => onView(customer)}><Eye size={14} /></Button><Button variant="ghost" size="icon" title="Edit" onClick={() => setDialog(customer)}><Pencil size={14} /></Button>{isAdmin && <Button variant="ghost" size="icon" title="Delete" onClick={() => isAdmin && setDeleteId(customer.id)}><Trash2 size={14} /></Button>}</div></td></tr>)}</tbody></table></div>{!rows.length && <EmptyState title={t(language, 'noCustomersFound')} description={t(language, 'trySearch')} />}<Pagination page={page} pages={pages} total={filtered.length} pageSize={pageSize} onPage={setPage} /></Card><CustomerDialog open={Boolean(dialog)} initial={typeof dialog === 'object' ? dialog : null} onClose={() => setDialog(null)} onSave={save} /><Dialog open={Boolean(deleteId)} title="Delete customer?" description="Customers with linked invoices cannot be removed by the API." onClose={() => setDeleteId(null)} footer={<><Button variant="outline" onClick={() => setDeleteId(null)}>Cancel</Button><Button variant="danger" onClick={remove}>Delete customer</Button></>}><p style={{ color: '#69758a', fontSize: 13 }}>{t(language, 'deletionWarning')}</p></Dialog></>
}

export function CustomerDialog({ open, initial, onClose, onSave }: { open: boolean; initial: Customer | null; onClose: () => void; onSave: (name: string) => void }) { const [name, setName] = useState(initial?.name || ''); useEffect(() => setName(initial?.name || ''), [initial, open]); return <Dialog open={open} title={initial ? 'Edit customer' : 'Add customer'} description="Keep customer contact records easy to find." onClose={onClose} footer={<><Button variant="outline" onClick={onClose}>Cancel</Button><Button onClick={() => onSave(name)} disabled={!name.trim()}>Save customer</Button></>}><div className="form-field"><label>Customer or company name</label><Input autoFocus value={name} onChange={(e) => setName(e.target.value)} placeholder="e.g. Golden Land Logistics" /></div></Dialog> }

export function CarsPage({ language, isAdmin, cars, customers, onView, onChange, notify }: { language: Language; isAdmin: boolean; cars: Car[]; customers: Customer[]; onView: (car: Car) => void; onChange: (value: Car[]) => void; notify: (message: string, kind?: Toast['kind']) => void }) {
  const [query, setQuery] = useState(''); const [page, setPage] = useState(1); const [dialog, setDialog] = useState<'new' | Car | null>(null); const [deleteId, setDeleteId] = useState<number | null>(null); const pageSize = 6; const filtered = cars.filter((car) => `${car.number} ${car.brand} ${car.model} ${car.customer?.name}`.toLowerCase().includes(query.toLowerCase())); const pages = Math.max(1, Math.ceil(filtered.length / pageSize)); const rows = filtered.slice((page - 1) * pageSize, page * pageSize); useEffect(() => setPage(1), [query])
  const save = async (data: CarForm) => { const payload = { number: data.number, brand: data.brand, model: data.model, customer_id: Number(data.customer_id) }; try { const result = typeof dialog === 'object' && dialog ? await api.updateCar(dialog.id, payload) : await api.createCar(payload); onChange(typeof dialog === 'object' && dialog ? cars.map((car) => car.id === dialog.id ? { ...car, ...result.data, customer: customers.find((customer) => customer.id === payload.customer_id) } : car) : [{ ...result.data, customer: customers.find((customer) => customer.id === payload.customer_id) }, ...cars]); setDialog(null); notify(typeof dialog === 'object' ? 'Vehicle updated' : 'Vehicle added') } catch (requestError) { notify(requestError instanceof Error ? requestError.message : 'Could not save vehicle to the live API.', 'error') } }
  const remove = async () => { if (!deleteId) return; try { await api.deleteCar(deleteId); onChange(cars.filter((car) => car.id !== deleteId)); setDeleteId(null); notify(t(language, 'vehicleDeleted')) } catch { notify(t(language, 'vehicleDeleteError'), 'error') } }
  return <><ListHeading eyebrow={t(language, 'vehicleDirectory')} title={t(language, 'vehicles')} description={t(language, 'vehicleDescription')} actionLabel={t(language, 'addVehicle')} onAction={() => setDialog('new')} /><div className="toolbar"><div className="search-box"><Search size={15} /><Input placeholder={t(language, 'searchVehicles')} value={query} onChange={(e) => setQuery(e.target.value)} /></div><span style={{ fontSize: 11, color: '#8892a4' }}>{filtered.length} {t(language, 'vehicles')}</span></div><Card className="table-card"><div className="table-wrap"><table className="data-table"><thead><tr><th>{t(language, 'vehicle')}</th><th>{t(language, 'makeModel')}</th><th>{t(language, 'owner')}</th><th>{t(language, 'serviceStatus')}</th><th></th></tr></thead><tbody>{rows.map((car) => <tr key={car.id}><td><div className="td-main"><span className="tiny-avatar" style={{ background: '#e8faf4', color: '#1aaf7b' }}><CarFront size={13} /></span><strong>{car.number}</strong></div></td><td>{[car.brand, car.model].filter(Boolean).join(' ') || '—'}</td><td>{car.customer?.name || customers.find((customer) => customer.id === car.customer_id)?.name || '—'}</td><td><Badge tone="success">{t(language, 'activeProfile')}</Badge></td><td><div className="table-actions"><Button variant="ghost" size="icon" title="View" onClick={() => onView(car)}><Eye size={14} /></Button><Button variant="ghost" size="icon" title="Edit" onClick={() => setDialog(car)}><Pencil size={14} /></Button>{isAdmin && <Button variant="ghost" size="icon" title="Delete" onClick={() => isAdmin && setDeleteId(car.id)}><Trash2 size={14} /></Button>}</div></td></tr>)}</tbody></table></div>{!rows.length && <EmptyState title={t(language, 'noVehiclesFound')} description={t(language, 'trySearch')} />}<Pagination page={page} pages={pages} total={filtered.length} pageSize={pageSize} onPage={setPage} /></Card><CarDialog open={Boolean(dialog)} initial={typeof dialog === 'object' ? dialog : null} customers={customers} onClose={() => setDialog(null)} onSave={save} /><Dialog open={Boolean(deleteId)} title="Delete vehicle?" description="Vehicles with linked invoices cannot be deleted." onClose={() => setDeleteId(null)} footer={<><Button variant="outline" onClick={() => setDeleteId(null)}>Cancel</Button><Button variant="danger" onClick={remove}>Delete vehicle</Button></>}><p style={{ color: '#69758a', fontSize: 13 }}>{t(language, 'deletionWarning')}</p></Dialog></>
}

export function CarDialog({ open, initial, customers, onClose, onSave }: { open: boolean; initial: Car | null; customers: Customer[]; onClose: () => void; onSave: (data: CarForm) => void }) { const [form, setForm] = useState<CarForm>({ number: initial?.number || '', brand: initial?.brand || '', model: initial?.model || '', customer_id: String(initial?.customer_id || customers[0]?.id || '') }); useEffect(() => setForm({ number: initial?.number || '', brand: initial?.brand || '', model: initial?.model || '', customer_id: String(initial?.customer_id || customers[0]?.id || '') }), [initial, open, customers]); const patch = (next: Partial<CarForm>) => setForm((value) => ({ ...value, ...next })); return <Dialog open={open} title={initial ? 'Edit vehicle' : 'Add vehicle'} description="Add the registration and owner details for a vehicle." onClose={onClose} footer={<><Button variant="outline" onClick={onClose}>Cancel</Button><Button onClick={() => onSave(form)} disabled={!form.number || !form.customer_id}>Save vehicle</Button></>}><div className="form-grid"><div className="form-field"><label>Vehicle number</label><Input autoFocus value={form.number} onChange={(e) => patch({ number: e.target.value })} placeholder="9H-4821" /></div><div className="form-field"><label>Customer</label><Select value={form.customer_id} onChange={(e) => patch({ customer_id: e.target.value })}>{customers.map((customer) => <option key={customer.id} value={customer.id}>{customer.name}</option>)}</Select></div><div className="form-field"><label>Brand</label><Input value={form.brand} onChange={(e) => patch({ brand: e.target.value })} placeholder="Hino" /></div><div className="form-field"><label>Model</label><Input value={form.model} onChange={(e) => patch({ model: e.target.value })} placeholder="500 Series" /></div></div></Dialog> }

export function ItemDetailPage({ language, item, invoices, onBack, onViewInvoice }: { language: Language; item: Item; invoices: Invoice[]; onBack: () => void; onViewInvoice: (invoice: Invoice) => void }) {
  const invoiceRows = invoices.flatMap((invoice) => invoice.details?.filter((detail) => detail.item_id === item.id || detail.item?.id === item.id || detail.item?.name === item.name || detail.name === item.name).map((detail) => ({ invoice, detail })) || [])
  return <><div className="page-heading"><div><button className="back-link" onClick={onBack}>← {t(language, 'services')}</button><div className="eyebrow">Service item profile</div><h1>{item.name}</h1><p>Invoice usage history with date, quantity, and price details.</p></div></div><div className="detail-grid"><Card><div className="detail-label">Service item</div><div className="detail-person"><div className="vehicle-icon" style={{ background: '#fff6dc', color: '#d39d1f' }}><ClipboardList size={19} /></div><div><h2>{item.name}</h2><p>Current listed price: {money(item.price)}</p></div></div></Card><Card><div className="detail-label">Invoices</div><div className="detail-payment"><strong>{invoiceRows.length}</strong><span>invoice line items using this service</span></div></Card><Card><div className="detail-label">Quantity</div><div className="detail-payment"><strong>{invoiceRows.reduce((sum, row) => sum + Number(row.detail.quantity || 0), 0)}</strong><span>total units recorded</span></div></Card></div><Card className="table-card"><div className="card-title detail-section-heading"><div><h2>Invoice summary</h2><p>Date, quantity, and price for every invoice using this item.</p></div><Badge tone="info">{invoiceRows.length} records</Badge></div>{invoiceRows.length ? <div className="table-wrap"><table className="data-table"><thead><tr><th>Invoice</th><th>Date</th><th>Customer</th><th>Vehicle</th><th>Quantity</th><th>Price</th><th>Total</th><th></th></tr></thead><tbody>{invoiceRows.map(({ invoice, detail }, index) => <tr key={`${invoice.id}-${detail.id || index}`}><td><button className="table-link" onClick={() => onViewInvoice(invoice)}>#{invoice.invoice_number}</button></td><td>{shortDate(invoice.date)}</td><td>{invoice.customer?.name || '—'}</td><td>{invoice.car?.number || '—'}</td><td>{detail.quantity}</td><td>{money(detail.price)}</td><td><strong>{money(Number(detail.price) * Number(detail.quantity))}</strong></td><td><Button variant="ghost" size="icon" title="View invoice" onClick={() => onViewInvoice(invoice)}><Eye size={14} /></Button></td></tr>)}</tbody></table></div> : <EmptyState title="No invoice usage found" description="This item has not been used on an invoice yet." />}</Card></>
}

export function ItemsPage({ language, isAdmin, items, invoices, onView, onChange, notify }: { language: Language; isAdmin: boolean; items: Item[]; invoices: Invoice[]; onView: (item: Item) => void; onChange: (items: Item[]) => void; notify: (message: string, kind?: Toast['kind']) => void }) {
  const [query, setQuery] = useState('')
  const [editing, setEditing] = useState<Item | null>(null)
  const [deleteId, setDeleteId] = useState<number | null>(null)
  const [name, setName] = useState('')
  const filtered = items.filter((item) => item.name.toLowerCase().includes(query.toLowerCase()))
  useEffect(() => setName(editing?.name || ''), [editing])
  const save = async () => {
    if (!editing || !name.trim()) return
    try {
      const result = await api.updateItem(editing.id, { name: name.trim() })
      onChange(items.map((item) => item.id === editing.id ? { ...item, ...result.data } : item))
      setEditing(null)
      notify(t(language, 'itemUpdated'))
    } catch { notify(t(language, 'itemUpdateError'), 'error') }
  }
  const remove = async () => {
    if (!deleteId) return
    try {
      await api.deleteItem(deleteId)
      onChange(items.filter((item) => item.id !== deleteId))
      setDeleteId(null)
      notify(t(language, 'itemDeleted'))
    } catch { notify(t(language, 'itemDeleteError'), 'error') }
  }
  return <><div className="page-heading"><div><h1>{t(language, 'services')}</h1><p>{t(language, 'serviceDescriptionText')}</p></div><span className="live-label">{t(language, 'liveApi')}</span></div><div className="toolbar"><div className="search-box"><Search size={15} /><Input placeholder={t(language, 'searchServices')} value={query} onChange={(e) => setQuery(e.target.value)} /></div><span style={{ fontSize: 11, color: '#8892a4' }}>{filtered.length} {t(language, 'services')}</span></div><Card className="table-card"><div className="table-wrap"><table className="data-table"><thead><tr><th>{t(language, 'service')}</th><th>{t(language, 'latestPrice')}</th><th>{t(language, 'usage')}</th><th></th></tr></thead><tbody>{filtered.map((item) => <tr key={item.id}><td><div className="td-main"><span className="tiny-avatar" style={{ background: '#fff6dc', color: '#d39d1f' }}><ClipboardList size={13} /></span><strong>{item.name}</strong></div></td><td>{money(item.price)}</td><td>{invoices.reduce((count, invoice) => count + (invoice.details?.some((detail) => detail.item_id === item.id || detail.item?.id === item.id || detail.item?.name === item.name || detail.name === item.name) ? 1 : 0), 0)} {t(language, 'invoices')}</td><td><div className="table-actions"><Button variant="ghost" size="icon" title="View" onClick={() => onView(item)}><Eye size={14} /></Button><Button variant="ghost" size="icon" title="Edit" onClick={() => setEditing(item)}><Pencil size={14} /></Button>{isAdmin && <Button variant="ghost" size="icon" title="Delete" onClick={() => setDeleteId(item.id)}><Trash2 size={14} /></Button>}</div></td></tr>)}</tbody></table></div>{!filtered.length && <EmptyState title={t(language, 'noServicesFound')} description={t(language, 'noServicesDescription')} />}<div className="pagination"><span>{t(language, 'showingServices')}</span></div></Card><Dialog open={Boolean(editing)} title="Edit item" description="Update the service item name used on invoices." onClose={() => setEditing(null)} footer={<><Button variant="outline" onClick={() => setEditing(null)}>Cancel</Button><Button onClick={save} disabled={!name.trim()}>Save item</Button></>}><div className="form-field"><label>Item name</label><Input autoFocus value={name} onChange={(event) => setName(event.target.value)} /></div></Dialog><Dialog open={Boolean(deleteId)} title="Delete item?" description="Only administrators can delete items." onClose={() => setDeleteId(null)} footer={<><Button variant="outline" onClick={() => setDeleteId(null)}>Cancel</Button><Button variant="danger" onClick={remove}>Delete item</Button></>}><p style={{ color: '#69758a', fontSize: 13 }}>{t(language, 'deletionWarning')}</p></Dialog></> }

export function ListHeading({ eyebrow, title, description, actionLabel, onAction }: { eyebrow?: string; title: string; description: string; actionLabel: string; onAction: () => void }) { return <div className="page-heading"><div>{eyebrow && <div className="eyebrow">{eyebrow}</div>}<h1>{title}</h1><p>{description}</p></div><div className="actions"><Button onClick={onAction}><Plus size={15} /> {actionLabel}</Button></div></div> }
