import React, { useEffect, useState } from 'react'
import { CarFront, ClipboardList, Eye, Pencil, Plus, Search, Trash2 } from 'lucide-react'
import type { Car, Customer, Invoice } from '../../services/apiServices'
import { api } from '../../services/apiServices'
import { initials, money, shortDate } from '../../lib/utils'
import { Badge, Button, Card, Dialog, EmptyState, Input, Select } from '../../components/ui'
import { type Language, type Toast, type CarForm, t } from '../../lib/app-shared'
import { InvoiceTable } from '../invoices/InvoiceList'
import { RelatedInvoices } from '../invoices/InvoiceDetail'
import { CarDialog } from './CarForm'
import { ListHeading } from '../../components/ListHeading'
import { Pagination } from '../../components/Pagination'



export function CarsPage({ language, isAdmin, cars, customers, onView, onChange, notify }: { language: Language; isAdmin: boolean; cars: Car[]; customers: Customer[]; onView: (car: Car) => void; onChange: (value: Car[]) => void; notify: (message: string, kind?: Toast['kind']) => void }) {
  const [query, setQuery] = useState(''); const [page, setPage] = useState(1); const [dialog, setDialog] = useState<'new' | Car | null>(null); const [deleteId, setDeleteId] = useState<number | null>(null); const pageSize = 6; const filtered = cars.filter((car) => `${car.number} ${car.brand} ${car.model} ${car.customer?.name}`.toLowerCase().includes(query.toLowerCase())); const pages = Math.max(1, Math.ceil(filtered.length / pageSize)); const rows = filtered.slice((page - 1) * pageSize, page * pageSize); useEffect(() => setPage(1), [query])
  const save = async (data: CarForm) => { const payload = { number: data.number, brand: data.brand, model: data.model, customer_id: Number(data.customer_id) }; try { const result = typeof dialog === 'object' && dialog ? await api.updateCar(dialog.id, payload) : await api.createCar(payload); onChange(typeof dialog === 'object' && dialog ? cars.map((car) => car.id === dialog.id ? { ...car, ...result.data, customer: customers.find((customer) => customer.id === payload.customer_id) } : car) : [{ ...result.data, customer: customers.find((customer) => customer.id === payload.customer_id) }, ...cars]); setDialog(null); notify(typeof dialog === 'object' ? 'Vehicle updated' : 'Vehicle added') } catch (requestError) { notify(requestError instanceof Error ? requestError.message : 'Could not save vehicle to the live API.', 'error') } }
  const remove = async () => { if (!deleteId) return; try { await api.deleteCar(deleteId); onChange(cars.filter((car) => car.id !== deleteId)); setDeleteId(null); notify(t(language, 'vehicleDeleted')) } catch { notify(t(language, 'vehicleDeleteError'), 'error') } }
  return <><ListHeading eyebrow={t(language, 'vehicleDirectory')} title={t(language, 'vehicles')} description={t(language, 'vehicleDescription')} actionLabel={t(language, 'addVehicle')} onAction={() => setDialog('new')} /><div className="toolbar"><div className="search-box"><Search size={15} /><Input placeholder={t(language, 'searchVehicles')} value={query} onChange={(e) => setQuery(e.target.value)} /></div><span style={{ fontSize: 11, color: '#8892a4' }}>{filtered.length} {t(language, 'vehicles')}</span></div><Card className="table-card"><div className="table-wrap"><table className="data-table"><thead><tr><th>{t(language, 'vehicle')}</th><th>{t(language, 'makeModel')}</th><th>{t(language, 'owner')}</th><th>{t(language, 'serviceStatus')}</th><th></th></tr></thead><tbody>{rows.map((car) => <tr key={car.id}><td><div className="td-main"><span className="tiny-avatar" style={{ background: '#e8faf4', color: '#1aaf7b' }}><CarFront size={13} /></span><strong>{car.number}</strong></div></td><td>{[car.brand, car.model].filter(Boolean).join(' ') || '—'}</td><td>{car.customer?.name || customers.find((customer) => customer.id === car.customer_id)?.name || '—'}</td><td><Badge tone="success">{t(language, 'activeProfile')}</Badge></td><td><div className="table-actions"><Button variant="ghost" size="icon" title="View" onClick={() => onView(car)}><Eye size={14} /></Button><Button variant="ghost" size="icon" title="Edit" onClick={() => setDialog(car)}><Pencil size={14} /></Button>{isAdmin && <Button variant="ghost" size="icon" title="Delete" onClick={() => isAdmin && setDeleteId(car.id)}><Trash2 size={14} /></Button>}</div></td></tr>)}</tbody></table></div>{!rows.length && <EmptyState title={t(language, 'noVehiclesFound')} description={t(language, 'trySearch')} />}<Pagination page={page} pages={pages} total={filtered.length} pageSize={pageSize} onPage={setPage} /></Card><CarDialog open={Boolean(dialog)} initial={typeof dialog === 'object' ? dialog : null} customers={customers} onClose={() => setDialog(null)} onSave={save} /><Dialog open={Boolean(deleteId)} title="Delete vehicle?" description="Vehicles with linked invoices cannot be deleted." onClose={() => setDeleteId(null)} footer={<><Button variant="outline" onClick={() => setDeleteId(null)}>Cancel</Button><Button variant="danger" onClick={remove}>Delete vehicle</Button></>}><p style={{ color: '#69758a', fontSize: 13 }}>{t(language, 'deletionWarning')}</p></Dialog></>
}
