import { ChevronsLeft, ChevronsRight, Download, LogOut, Settings, ShieldCheck } from 'lucide-react'
import type { User } from '../lib/api'
import { initials, cn } from '../lib/utils'
import { type PageName, type Language, navItems, t, activeNavPage } from '../lib/app-shared'

export function Sidebar({ page, collapsed, language, user, onToggle, onNavigate, onSignOut, onDownloadDatabase }: { page: PageName; collapsed: boolean; language: Language; user: User; onToggle: () => void; onNavigate: (page: PageName) => void; onSignOut: () => void; onDownloadDatabase: () => void }) {
  const isAdmin = user.role_id === 1
  const activePage = activeNavPage(page)
  return <aside className={cn('sidebar', collapsed && 'collapsed')}><div className="brand"><div className="brand-mark">H</div><div className="brand-copy"><strong>HTOO</strong><small>Heavy Vehicle</small></div><button className="sidebar-toggle icon-button" onClick={onToggle} title={collapsed ? 'Expand sidebar' : 'Collapse sidebar'} aria-label={collapsed ? 'Expand sidebar' : 'Collapse sidebar'}>{collapsed ? <ChevronsRight size={16} /> : <ChevronsLeft size={16} />}</button></div><div className="nav-label">{t(language, 'mainMenu')}</div><nav className="nav">{navItems.map(({ id, labelKey, icon: Icon }) => <button key={id} className={activePage === id ? 'active' : ''} onClick={() => onNavigate(id)} title={t(language, labelKey)}><Icon size={17} strokeWidth={1.8} /><span>{t(language, labelKey)}</span></button>)}</nav><div className="sidebar-bottom"><div className="nav-label">{t(language, 'workspace')}</div><nav className="nav"><button className={activePage === 'settings' ? 'active' : ''} onClick={() => onNavigate('settings')} title={t(language, 'settings')}><Settings size={17} strokeWidth={1.8} /><span>{t(language, 'settings')}</span></button>{isAdmin && <button className={activePage === 'team-access' ? 'active' : ''} onClick={() => onNavigate('team-access')} title="Team access"><ShieldCheck size={17} strokeWidth={1.8} /><span>Team access</span></button>}{isAdmin && <button onClick={onDownloadDatabase} title={t(language, 'downloadDatabase')}><Download size={17} strokeWidth={1.8} /><span>{t(language, 'downloadDatabase')}</span></button>}<button onClick={onSignOut} title={t(language, 'signOut')}><LogOut size={17} strokeWidth={1.8} /><span>{t(language, 'signOut')}</span></button></nav><div className="user-card"><div className="avatar">{initials(user.name)}</div><div className="user-copy" style={{ flex: 1, minWidth: 0 }}><strong>{user.name}</strong><small>{user.email}</small></div></div></div></aside>
}
