import React, { useEffect, useState } from 'react'
import { CarFront, ClipboardList, Eye, Pencil, Plus, Search, Trash2 } from 'lucide-react'
import type { Car, Customer, Invoice } from '../../services/apiServices'
import { api } from '../../services/apiServices'
import { initials, money, shortDate } from '../../lib/utils'
import { Badge, Button, Card, Dialog, EmptyState, Input, Select } from '../../components/ui'
import { type Language, type Toast, type CarForm, t } from '../../lib/app-shared'
import { InvoiceTable } from '../invoices/InvoiceList'
import { RelatedInvoices } from '../invoices/InvoiceDetail'
import { CustomerDialog } from './CustomerForm'
import { ListHeading } from '../../components/ListHeading'
import { Pagination } from '../../components/Pagination'



export function CustomersPage({ language, isAdmin, customers, onView, onChange, notify }: { language: Language; isAdmin: boolean; customers: Customer[]; onView: (customer: Customer) => void; onChange: (value: Customer[]) => void; notify: (message: string, kind?: Toast['kind']) => void }) {
  const [query, setQuery] = useState(''); const [page, setPage] = useState(1); const [dialog, setDialog] = useState<'new' | Customer | null>(null); const [deleteId, setDeleteId] = useState<number | null>(null); const pageSize = 6; const filtered = customers.filter((customer) => `${customer.name} ${customer.phone || ''}`.toLowerCase().includes(query.toLowerCase())); const pages = Math.max(1, Math.ceil(filtered.length / pageSize)); const rows = filtered.slice((page - 1) * pageSize, page * pageSize); useEffect(() => setPage(1), [query])
  const save = async (name: string) => { try { const result = typeof dialog === 'object' && dialog ? await api.updateCustomer(dialog.id, { name }) : await api.createCustomer({ name }); onChange(typeof dialog === 'object' && dialog ? customers.map((customer) => customer.id === dialog.id ? { ...customer, ...result.data } : customer) : [{ ...result.data, _count: { invoices: 0, cars: 0 } }, ...customers]); setDialog(null); notify(typeof dialog === 'object' ? 'Customer updated' : 'Customer added') } catch (requestError) { notify(requestError instanceof Error ? requestError.message : 'Could not save customer to the live API.', 'error') } }
  const remove = async () => { if (!deleteId) return; try { await api.deleteCustomer(deleteId); onChange(customers.filter((customer) => customer.id !== deleteId)); setDeleteId(null); notify(t(language, 'customerDeleted')) } catch { notify(t(language, 'customerDeleteError'), 'error') } }
  return <><ListHeading eyebrow={t(language, 'customerDirectory')} title={t(language, 'customers')} description={t(language, 'customerDescription')} actionLabel={t(language, 'addCustomer')} onAction={() => setDialog('new')} /><div className="toolbar"><div className="toolbar-left"><div className="search-box"><Search size={15} /><Input placeholder={t(language, 'searchCustomers')} value={query} onChange={(e) => setQuery(e.target.value)} /></div></div><span style={{ fontSize: 11, color: '#8892a4' }}>{filtered.length} {t(language, 'customers')}</span></div><Card className="table-card"><div className="table-wrap"><table className="data-table"><thead><tr><th>{t(language, 'customer')}</th><th>{t(language, 'phone')}</th><th>{t(language, 'vehicles')}</th><th>{t(language, 'invoices')}</th><th></th></tr></thead><tbody>{rows.map((customer) => <tr key={customer.id}><td><div className="td-main"><span className="tiny-avatar">{initials(customer.name)}</span><strong>{customer.name}</strong></div></td><td>{customer.phone || '—'}</td><td>{customer._count?.cars || 0}</td><td>{customer._count?.invoices || 0}</td><td><div className="table-actions"><Button variant="ghost" size="icon" title="View" onClick={() => onView(customer)}><Eye size={14} /></Button><Button variant="ghost" size="icon" title="Edit" onClick={() => setDialog(customer)}><Pencil size={14} /></Button>{isAdmin && <Button variant="ghost" size="icon" title="Delete" onClick={() => isAdmin && setDeleteId(customer.id)}><Trash2 size={14} /></Button>}</div></td></tr>)}</tbody></table></div>{!rows.length && <EmptyState title={t(language, 'noCustomersFound')} description={t(language, 'trySearch')} />}<Pagination page={page} pages={pages} total={filtered.length} pageSize={pageSize} onPage={setPage} /></Card><CustomerDialog open={Boolean(dialog)} initial={typeof dialog === 'object' ? dialog : null} onClose={() => setDialog(null)} onSave={save} /><Dialog open={Boolean(deleteId)} title="Delete customer?" description="Customers with linked invoices cannot be removed by the API." onClose={() => setDeleteId(null)} footer={<><Button variant="outline" onClick={() => setDeleteId(null)}>Cancel</Button><Button variant="danger" onClick={remove}>Delete customer</Button></>}><p style={{ color: '#69758a', fontSize: 13 }}>{t(language, 'deletionWarning')}</p></Dialog></>
}
